
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pool: 'dremio-agent'

trigger:
- main

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm run build
  displayName: 'npm  build'
  

- task: CopyFiles@2
  inputs:
    Contents: |
      !server.js
      !pm2-process.json
      **
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    #overWrite: false # Optional
    #flattenFolders: false # Optional
    

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: '$(Build.ArtifactStagingDirectory)'
#     artifactName: drop

#- script: gulp  

- script: pm2 restart 'DREMIO API'
  displayName: 'restart PM2'